INTERESTS = {
  arts: ["Museums, Exhibitions & Galleries", "Photography & Film Creation", "Theatre, Musicals & Opera", "Live music or comedy", "Cinema", "Reading and Literature"],
  sports: ["Ball sports", "Endurance sports", "Wellbeing sports", "Snow sports", "Extreme sports", "Watersports"],
  films: ["Romance & Comedy", "Action", "Horror", "Documentary", "Animation & Cartoon", "Science Fiction"],
  music: ["Pop", "Electronic", "Classical & Opera", "Rock & Heavy Metal", "Jazz", "Hip Hop & Rap"],
  holiday: ["Relaxing beach holiday", "Trekking adventure", "City-break (Shopping, Food and Chill)", "Party holiday", "Stay-at-home holiday", "Historical city exploration"],
  food: ["A vegy salad", "Meat is all I need", "Quick pasta meal", "Let’s go out for dinner", "Delivery to my bed", "Whatever the food is, the drink is more important"]
};

MATCHING = {
  art_museum: "Museums, Exhibitions & Galleries",
  art_photography: "Photography & Film Creation",
  art_theatre: "Theatre, Musicals & Opera",
  art_live: "Live music or comedy",
  art_cinema: "Cinema",
  art_reading: "Reading and Literature",
  sport_ball: "Ball sports",
  sport_endurance: "Endurance sports",
  sport_wellbeing: "Wellbeing sports",
  sport_snow: "Snow sports",
  sport_extreme: "Extreme sports",
  sport_watersports: "Watersports",
  film_romcom: "Romance & Comedy",
  film_action: "Action",
  film_horror: "Horror",
  film_documentary: "Documentary",
  film_animation: "Animation & Cartoon",
  film_scifi: "Science Fiction",
  music_pop: "Pop",
  music_electronic: "Electronic",
  music_classical: "Classical & Opera",
  music_rock: "Rock & Heavy Metal",
  music_jazz: "Jazz",
  music_hiphop: "Hip Hop & Rap",
  holiday_beach: "Relaxing beach holiday",
  holiday_trek: "Trekking adventure",
  holiday_city: "City-break (Shop, Food, Chill)",
  holiday_party: "Party holiday",
  holiday_home: "Stay-at-home holiday",
  holiday_historic: "Historic city exploration",
  food_vegetarian: "A vegy salad",
  food_meat: "Meat is all I need",
  food_quick: "Quick pasta meal",
  food_restaurant: "Let’s go out for dinner",
  food_delivery: "Delivery to my bed",
  food_drink: "Only the drink matters",
}
